Try using action-junit-report to display test result

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -45,7 +45,13 @@ jobs:
     
     - name: Run Tests
       continue-on-error: true
-      run: ctest --preset ${{ matrix.preset }} --output-junit test.xml
+      run: ctest --preset ${{ matrix.preset }} --output-junit ctest-report.xml
     
     - name: Print Test Result
-      run: cat build/test.xml
+      run: cat build/ctest-report.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'build/ctest-report.xml'
